// Code generated by entc, DO NOT EDIT.

package whatsapp

import (
	"profissional/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.WhatsApp {
	return predicate.WhatsApp(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.WhatsApp {
	return predicate.WhatsApp(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.WhatsApp {
	return predicate.WhatsApp(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.WhatsApp {
	return predicate.WhatsApp(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.WhatsApp {
	return predicate.WhatsApp(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.WhatsApp {
	return predicate.WhatsApp(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.WhatsApp {
	return predicate.WhatsApp(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.WhatsApp {
	return predicate.WhatsApp(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.WhatsApp {
	return predicate.WhatsApp(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Numero applies equality check predicate on the "numero" field. It's identical to NumeroEQ.
func Numero(v int64) predicate.WhatsApp {
	return predicate.WhatsApp(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNumero), v))
	})
}

// Principal applies equality check predicate on the "principal" field. It's identical to PrincipalEQ.
func Principal(v bool) predicate.WhatsApp {
	return predicate.WhatsApp(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPrincipal), v))
	})
}

// NumeroEQ applies the EQ predicate on the "numero" field.
func NumeroEQ(v int64) predicate.WhatsApp {
	return predicate.WhatsApp(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNumero), v))
	})
}

// NumeroNEQ applies the NEQ predicate on the "numero" field.
func NumeroNEQ(v int64) predicate.WhatsApp {
	return predicate.WhatsApp(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldNumero), v))
	})
}

// NumeroIn applies the In predicate on the "numero" field.
func NumeroIn(vs ...int64) predicate.WhatsApp {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.WhatsApp(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldNumero), v...))
	})
}

// NumeroNotIn applies the NotIn predicate on the "numero" field.
func NumeroNotIn(vs ...int64) predicate.WhatsApp {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.WhatsApp(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldNumero), v...))
	})
}

// NumeroGT applies the GT predicate on the "numero" field.
func NumeroGT(v int64) predicate.WhatsApp {
	return predicate.WhatsApp(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldNumero), v))
	})
}

// NumeroGTE applies the GTE predicate on the "numero" field.
func NumeroGTE(v int64) predicate.WhatsApp {
	return predicate.WhatsApp(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldNumero), v))
	})
}

// NumeroLT applies the LT predicate on the "numero" field.
func NumeroLT(v int64) predicate.WhatsApp {
	return predicate.WhatsApp(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldNumero), v))
	})
}

// NumeroLTE applies the LTE predicate on the "numero" field.
func NumeroLTE(v int64) predicate.WhatsApp {
	return predicate.WhatsApp(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldNumero), v))
	})
}

// PrincipalEQ applies the EQ predicate on the "principal" field.
func PrincipalEQ(v bool) predicate.WhatsApp {
	return predicate.WhatsApp(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPrincipal), v))
	})
}

// PrincipalNEQ applies the NEQ predicate on the "principal" field.
func PrincipalNEQ(v bool) predicate.WhatsApp {
	return predicate.WhatsApp(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPrincipal), v))
	})
}

// HasProfissional applies the HasEdge predicate on the "profissional" edge.
func HasProfissional() predicate.WhatsApp {
	return predicate.WhatsApp(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ProfissionalTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProfissionalTable, ProfissionalColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProfissionalWith applies the HasEdge predicate on the "profissional" edge with a given conditions (other predicates).
func HasProfissionalWith(preds ...predicate.Profissional) predicate.WhatsApp {
	return predicate.WhatsApp(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ProfissionalInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProfissionalTable, ProfissionalColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WhatsApp) predicate.WhatsApp {
	return predicate.WhatsApp(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WhatsApp) predicate.WhatsApp {
	return predicate.WhatsApp(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WhatsApp) predicate.WhatsApp {
	return predicate.WhatsApp(func(s *sql.Selector) {
		p(s.Not())
	})
}
