CREATE USER 'root'@'%' IDENTIFIED BY 'root';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;

CREATE
    DATABASE IF NOT EXISTS profissionais;

CREATE
    DATABASE IF NOT EXISTS enderecos;

CREATE
    DATABASE IF NOT EXISTS unidades;

CREATE
    DATABASE IF NOT EXISTS materias;
