// Code generated by entc, DO NOT EDIT.

package podcast

const (
	// Label holds the string label denoting the podcast type in the database.
	Label = "podcast"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitulo holds the string denoting the titulo field in the database.
	FieldTitulo = "titulo"
	// FieldCodigo holds the string denoting the codigo field in the database.
	FieldCodigo = "codigo"
	// EdgeProfissional holds the string denoting the profissional edge name in mutations.
	EdgeProfissional = "profissional"
	// Table holds the table name of the podcast in the database.
	Table = "podcasts"
	// ProfissionalTable is the table that holds the profissional relation/edge.
	ProfissionalTable = "podcasts"
	// ProfissionalInverseTable is the table name for the Profissional entity.
	// It exists in this package in order to avoid circular dependency with the "profissional" package.
	ProfissionalInverseTable = "profissionals"
	// ProfissionalColumn is the table column denoting the profissional relation/edge.
	ProfissionalColumn = "profissional_podcasts"
)

// Columns holds all SQL columns for podcast fields.
var Columns = []string{
	FieldID,
	FieldTitulo,
	FieldCodigo,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "podcasts"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"profissional_podcasts",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
