// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CategoriaColumns holds the columns for the "categoria" table.
	CategoriaColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "descricao", Type: field.TypeString},
	}
	// CategoriaTable holds the schema information for the "categoria" table.
	CategoriaTable = &schema.Table{
		Name:       "categoria",
		Columns:    CategoriaColumns,
		PrimaryKey: []*schema.Column{CategoriaColumns[0]},
	}
	// MateriaColumns holds the columns for the "materia" table.
	MateriaColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "unidade_id", Type: field.TypeInt},
		{Name: "titulo", Type: field.TypeString},
		{Name: "url_amigavel", Type: field.TypeString, Unique: true},
		{Name: "data_agendamento", Type: field.TypeTime, Nullable: true},
		{Name: "fonte", Type: field.TypeString, Nullable: true},
		{Name: "link_fonte", Type: field.TypeString, Nullable: true},
		{Name: "texto", Type: field.TypeString, Size: 2147483647},
		{Name: "imagem_url", Type: field.TypeString, Nullable: true},
		{Name: "patrocinado", Type: field.TypeBool, Default: false},
		{Name: "status", Type: field.TypeBool, Default: true},
		{Name: "categoria_materias", Type: field.TypeInt, Nullable: true},
	}
	// MateriaTable holds the schema information for the "materia" table.
	MateriaTable = &schema.Table{
		Name:       "materia",
		Columns:    MateriaColumns,
		PrimaryKey: []*schema.Column{MateriaColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "materia_categoria_materias",
				Columns:    []*schema.Column{MateriaColumns[11]},
				RefColumns: []*schema.Column{CategoriaColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ProfissionalMateriasColumns holds the columns for the "profissional_materias" table.
	ProfissionalMateriasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "profissional_id", Type: field.TypeInt},
		{Name: "materia_profissional_materias", Type: field.TypeInt, Nullable: true},
	}
	// ProfissionalMateriasTable holds the schema information for the "profissional_materias" table.
	ProfissionalMateriasTable = &schema.Table{
		Name:       "profissional_materias",
		Columns:    ProfissionalMateriasColumns,
		PrimaryKey: []*schema.Column{ProfissionalMateriasColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "profissional_materias_materia_profissional_materias",
				Columns:    []*schema.Column{ProfissionalMateriasColumns[2]},
				RefColumns: []*schema.Column{MateriaColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CategoriaTable,
		MateriaTable,
		ProfissionalMateriasTable,
	}
)

func init() {
	MateriaTable.ForeignKeys[0].RefTable = CategoriaTable
	ProfissionalMateriasTable.ForeignKeys[0].RefTable = MateriaTable
}
