// Code generated by entc, DO NOT EDIT.

package ent

import (
	"profissional/ent/profissional"
	"profissional/ent/schema"
	"profissional/ent/whatsapp"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	profissionalMixin := schema.Profissional{}.Mixin()
	profissionalMixinFields0 := profissionalMixin[0].Fields()
	_ = profissionalMixinFields0
	profissionalFields := schema.Profissional{}.Fields()
	_ = profissionalFields
	// profissionalDescCreateTime is the schema descriptor for create_time field.
	profissionalDescCreateTime := profissionalMixinFields0[0].Descriptor()
	// profissional.DefaultCreateTime holds the default value on creation for the create_time field.
	profissional.DefaultCreateTime = profissionalDescCreateTime.Default.(func() time.Time)
	// profissionalDescUpdateTime is the schema descriptor for update_time field.
	profissionalDescUpdateTime := profissionalMixinFields0[1].Descriptor()
	// profissional.DefaultUpdateTime holds the default value on creation for the update_time field.
	profissional.DefaultUpdateTime = profissionalDescUpdateTime.Default.(func() time.Time)
	// profissional.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	profissional.UpdateDefaultUpdateTime = profissionalDescUpdateTime.UpdateDefault.(func() time.Time)
	// profissionalDescNome is the schema descriptor for nome field.
	profissionalDescNome := profissionalFields[0].Descriptor()
	// profissional.NomeValidator is a validator for the "nome" field. It is called by the builders before save.
	profissional.NomeValidator = profissionalDescNome.Validators[0].(func(string) error)
	// profissionalDescURLAmigavel is the schema descriptor for url_amigavel field.
	profissionalDescURLAmigavel := profissionalFields[1].Descriptor()
	// profissional.URLAmigavelValidator is a validator for the "url_amigavel" field. It is called by the builders before save.
	profissional.URLAmigavelValidator = profissionalDescURLAmigavel.Validators[0].(func(string) error)
	// profissionalDescRecomendado is the schema descriptor for recomendado field.
	profissionalDescRecomendado := profissionalFields[2].Descriptor()
	// profissional.DefaultRecomendado holds the default value on creation for the recomendado field.
	profissional.DefaultRecomendado = profissionalDescRecomendado.Default.(bool)
	// profissionalDescAtivo is the schema descriptor for ativo field.
	profissionalDescAtivo := profissionalFields[3].Descriptor()
	// profissional.DefaultAtivo holds the default value on creation for the ativo field.
	profissional.DefaultAtivo = profissionalDescAtivo.Default.(bool)
	// profissionalDescUnidadeID is the schema descriptor for unidade_id field.
	profissionalDescUnidadeID := profissionalFields[15].Descriptor()
	// profissional.UnidadeIDValidator is a validator for the "unidade_id" field. It is called by the builders before save.
	profissional.UnidadeIDValidator = profissionalDescUnidadeID.Validators[0].(func(int) error)
	// profissionalDescEnderecoID is the schema descriptor for endereco_id field.
	profissionalDescEnderecoID := profissionalFields[16].Descriptor()
	// profissional.EnderecoIDValidator is a validator for the "endereco_id" field. It is called by the builders before save.
	profissional.EnderecoIDValidator = profissionalDescEnderecoID.Validators[0].(func(int) error)
	whatsappFields := schema.WhatsApp{}.Fields()
	_ = whatsappFields
	// whatsappDescPrincipal is the schema descriptor for principal field.
	whatsappDescPrincipal := whatsappFields[1].Descriptor()
	// whatsapp.DefaultPrincipal holds the default value on creation for the principal field.
	whatsapp.DefaultPrincipal = whatsappDescPrincipal.Default.(bool)
}
