// Code generated by entc, DO NOT EDIT.

package endereco

import (
	"endereco/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Endereco {
	return predicate.Endereco(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Endereco {
	return predicate.Endereco(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Endereco {
	return predicate.Endereco(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Endereco {
	return predicate.Endereco(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Endereco {
	return predicate.Endereco(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Endereco {
	return predicate.Endereco(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Endereco {
	return predicate.Endereco(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Endereco {
	return predicate.Endereco(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Endereco {
	return predicate.Endereco(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Numero applies equality check predicate on the "numero" field. It's identical to NumeroEQ.
func Numero(v string) predicate.Endereco {
	return predicate.Endereco(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNumero), v))
	})
}

// NumeroEQ applies the EQ predicate on the "numero" field.
func NumeroEQ(v string) predicate.Endereco {
	return predicate.Endereco(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNumero), v))
	})
}

// NumeroNEQ applies the NEQ predicate on the "numero" field.
func NumeroNEQ(v string) predicate.Endereco {
	return predicate.Endereco(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldNumero), v))
	})
}

// NumeroIn applies the In predicate on the "numero" field.
func NumeroIn(vs ...string) predicate.Endereco {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Endereco(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldNumero), v...))
	})
}

// NumeroNotIn applies the NotIn predicate on the "numero" field.
func NumeroNotIn(vs ...string) predicate.Endereco {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Endereco(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldNumero), v...))
	})
}

// NumeroGT applies the GT predicate on the "numero" field.
func NumeroGT(v string) predicate.Endereco {
	return predicate.Endereco(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldNumero), v))
	})
}

// NumeroGTE applies the GTE predicate on the "numero" field.
func NumeroGTE(v string) predicate.Endereco {
	return predicate.Endereco(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldNumero), v))
	})
}

// NumeroLT applies the LT predicate on the "numero" field.
func NumeroLT(v string) predicate.Endereco {
	return predicate.Endereco(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldNumero), v))
	})
}

// NumeroLTE applies the LTE predicate on the "numero" field.
func NumeroLTE(v string) predicate.Endereco {
	return predicate.Endereco(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldNumero), v))
	})
}

// NumeroContains applies the Contains predicate on the "numero" field.
func NumeroContains(v string) predicate.Endereco {
	return predicate.Endereco(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldNumero), v))
	})
}

// NumeroHasPrefix applies the HasPrefix predicate on the "numero" field.
func NumeroHasPrefix(v string) predicate.Endereco {
	return predicate.Endereco(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldNumero), v))
	})
}

// NumeroHasSuffix applies the HasSuffix predicate on the "numero" field.
func NumeroHasSuffix(v string) predicate.Endereco {
	return predicate.Endereco(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldNumero), v))
	})
}

// NumeroEqualFold applies the EqualFold predicate on the "numero" field.
func NumeroEqualFold(v string) predicate.Endereco {
	return predicate.Endereco(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldNumero), v))
	})
}

// NumeroContainsFold applies the ContainsFold predicate on the "numero" field.
func NumeroContainsFold(v string) predicate.Endereco {
	return predicate.Endereco(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldNumero), v))
	})
}

// HasCep applies the HasEdge predicate on the "cep" edge.
func HasCep() predicate.Endereco {
	return predicate.Endereco(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(CepTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CepTable, CepColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCepWith applies the HasEdge predicate on the "cep" edge with a given conditions (other predicates).
func HasCepWith(preds ...predicate.Cep) predicate.Endereco {
	return predicate.Endereco(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(CepInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CepTable, CepColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Endereco) predicate.Endereco {
	return predicate.Endereco(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Endereco) predicate.Endereco {
	return predicate.Endereco(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Endereco) predicate.Endereco {
	return predicate.Endereco(func(s *sql.Selector) {
		p(s.Not())
	})
}
