// Code generated by entc, DO NOT EDIT.

package ent

import (
	"endereco/ent/cep"
	"endereco/ent/cidade"
	"endereco/ent/endereco"
	"endereco/ent/estado"
	"endereco/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cepFields := schema.Cep{}.Fields()
	_ = cepFields
	// cepDescLogradouro is the schema descriptor for logradouro field.
	cepDescLogradouro := cepFields[1].Descriptor()
	// cep.LogradouroValidator is a validator for the "logradouro" field. It is called by the builders before save.
	cep.LogradouroValidator = cepDescLogradouro.Validators[0].(func(string) error)
	// cepDescBairro is the schema descriptor for bairro field.
	cepDescBairro := cepFields[2].Descriptor()
	// cep.BairroValidator is a validator for the "bairro" field. It is called by the builders before save.
	cep.BairroValidator = cepDescBairro.Validators[0].(func(string) error)
	// cepDescID is the schema descriptor for id field.
	cepDescID := cepFields[0].Descriptor()
	// cep.IDValidator is a validator for the "id" field. It is called by the builders before save.
	cep.IDValidator = func() func(int32) error {
		validators := cepDescID.Validators
		fns := [...]func(int32) error{
			validators[0].(func(int32) error),
			validators[1].(func(int32) error),
		}
		return func(id int32) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	cidadeFields := schema.Cidade{}.Fields()
	_ = cidadeFields
	// cidadeDescNome is the schema descriptor for nome field.
	cidadeDescNome := cidadeFields[0].Descriptor()
	// cidade.NomeValidator is a validator for the "nome" field. It is called by the builders before save.
	cidade.NomeValidator = cidadeDescNome.Validators[0].(func(string) error)
	enderecoMixin := schema.Endereco{}.Mixin()
	enderecoMixinFields0 := enderecoMixin[0].Fields()
	_ = enderecoMixinFields0
	enderecoFields := schema.Endereco{}.Fields()
	_ = enderecoFields
	// enderecoDescCreateTime is the schema descriptor for create_time field.
	enderecoDescCreateTime := enderecoMixinFields0[0].Descriptor()
	// endereco.DefaultCreateTime holds the default value on creation for the create_time field.
	endereco.DefaultCreateTime = enderecoDescCreateTime.Default.(func() time.Time)
	// enderecoDescUpdateTime is the schema descriptor for update_time field.
	enderecoDescUpdateTime := enderecoMixinFields0[1].Descriptor()
	// endereco.DefaultUpdateTime holds the default value on creation for the update_time field.
	endereco.DefaultUpdateTime = enderecoDescUpdateTime.Default.(func() time.Time)
	// endereco.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	endereco.UpdateDefaultUpdateTime = enderecoDescUpdateTime.UpdateDefault.(func() time.Time)
	// enderecoDescNumero is the schema descriptor for numero field.
	enderecoDescNumero := enderecoFields[0].Descriptor()
	// endereco.NumeroValidator is a validator for the "numero" field. It is called by the builders before save.
	endereco.NumeroValidator = enderecoDescNumero.Validators[0].(func(string) error)
	estadoFields := schema.Estado{}.Fields()
	_ = estadoFields
	// estadoDescNome is the schema descriptor for nome field.
	estadoDescNome := estadoFields[0].Descriptor()
	// estado.NomeValidator is a validator for the "nome" field. It is called by the builders before save.
	estado.NomeValidator = estadoDescNome.Validators[0].(func(string) error)
}
