// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"materia/ent/predicate"
	"materia/ent/profissionalmaterias"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProfissionalMateriasDelete is the builder for deleting a ProfissionalMaterias entity.
type ProfissionalMateriasDelete struct {
	config
	hooks    []Hook
	mutation *ProfissionalMateriasMutation
}

// Where appends a list predicates to the ProfissionalMateriasDelete builder.
func (pmd *ProfissionalMateriasDelete) Where(ps ...predicate.ProfissionalMaterias) *ProfissionalMateriasDelete {
	pmd.mutation.Where(ps...)
	return pmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pmd *ProfissionalMateriasDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pmd.hooks) == 0 {
		affected, err = pmd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProfissionalMateriasMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pmd.mutation = mutation
			affected, err = pmd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pmd.hooks) - 1; i >= 0; i-- {
			if pmd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pmd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pmd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (pmd *ProfissionalMateriasDelete) ExecX(ctx context.Context) int {
	n, err := pmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pmd *ProfissionalMateriasDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: profissionalmaterias.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: profissionalmaterias.FieldID,
			},
		},
	}
	if ps := pmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, pmd.driver, _spec)
}

// ProfissionalMateriasDeleteOne is the builder for deleting a single ProfissionalMaterias entity.
type ProfissionalMateriasDeleteOne struct {
	pmd *ProfissionalMateriasDelete
}

// Exec executes the deletion query.
func (pmdo *ProfissionalMateriasDeleteOne) Exec(ctx context.Context) error {
	n, err := pmdo.pmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{profissionalmaterias.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pmdo *ProfissionalMateriasDeleteOne) ExecX(ctx context.Context) {
	pmdo.pmd.ExecX(ctx)
}
