// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"materia/ent/materia"
	"materia/ent/predicate"
	"materia/ent/profissionalmaterias"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProfissionalMateriasQuery is the builder for querying ProfissionalMaterias entities.
type ProfissionalMateriasQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ProfissionalMaterias
	// eager-loading edges.
	withMateria *MateriaQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProfissionalMateriasQuery builder.
func (pmq *ProfissionalMateriasQuery) Where(ps ...predicate.ProfissionalMaterias) *ProfissionalMateriasQuery {
	pmq.predicates = append(pmq.predicates, ps...)
	return pmq
}

// Limit adds a limit step to the query.
func (pmq *ProfissionalMateriasQuery) Limit(limit int) *ProfissionalMateriasQuery {
	pmq.limit = &limit
	return pmq
}

// Offset adds an offset step to the query.
func (pmq *ProfissionalMateriasQuery) Offset(offset int) *ProfissionalMateriasQuery {
	pmq.offset = &offset
	return pmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pmq *ProfissionalMateriasQuery) Unique(unique bool) *ProfissionalMateriasQuery {
	pmq.unique = &unique
	return pmq
}

// Order adds an order step to the query.
func (pmq *ProfissionalMateriasQuery) Order(o ...OrderFunc) *ProfissionalMateriasQuery {
	pmq.order = append(pmq.order, o...)
	return pmq
}

// QueryMateria chains the current query on the "materia" edge.
func (pmq *ProfissionalMateriasQuery) QueryMateria() *MateriaQuery {
	query := &MateriaQuery{config: pmq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(profissionalmaterias.Table, profissionalmaterias.FieldID, selector),
			sqlgraph.To(materia.Table, materia.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, profissionalmaterias.MateriaTable, profissionalmaterias.MateriaColumn),
		)
		fromU = sqlgraph.SetNeighbors(pmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProfissionalMaterias entity from the query.
// Returns a *NotFoundError when no ProfissionalMaterias was found.
func (pmq *ProfissionalMateriasQuery) First(ctx context.Context) (*ProfissionalMaterias, error) {
	nodes, err := pmq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{profissionalmaterias.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pmq *ProfissionalMateriasQuery) FirstX(ctx context.Context) *ProfissionalMaterias {
	node, err := pmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProfissionalMaterias ID from the query.
// Returns a *NotFoundError when no ProfissionalMaterias ID was found.
func (pmq *ProfissionalMateriasQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pmq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{profissionalmaterias.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pmq *ProfissionalMateriasQuery) FirstIDX(ctx context.Context) int {
	id, err := pmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProfissionalMaterias entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one ProfissionalMaterias entity is not found.
// Returns a *NotFoundError when no ProfissionalMaterias entities are found.
func (pmq *ProfissionalMateriasQuery) Only(ctx context.Context) (*ProfissionalMaterias, error) {
	nodes, err := pmq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{profissionalmaterias.Label}
	default:
		return nil, &NotSingularError{profissionalmaterias.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pmq *ProfissionalMateriasQuery) OnlyX(ctx context.Context) *ProfissionalMaterias {
	node, err := pmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProfissionalMaterias ID in the query.
// Returns a *NotSingularError when exactly one ProfissionalMaterias ID is not found.
// Returns a *NotFoundError when no entities are found.
func (pmq *ProfissionalMateriasQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pmq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{profissionalmaterias.Label}
	default:
		err = &NotSingularError{profissionalmaterias.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pmq *ProfissionalMateriasQuery) OnlyIDX(ctx context.Context) int {
	id, err := pmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProfissionalMateriasSlice.
func (pmq *ProfissionalMateriasQuery) All(ctx context.Context) ([]*ProfissionalMaterias, error) {
	if err := pmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return pmq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (pmq *ProfissionalMateriasQuery) AllX(ctx context.Context) []*ProfissionalMaterias {
	nodes, err := pmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProfissionalMaterias IDs.
func (pmq *ProfissionalMateriasQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := pmq.Select(profissionalmaterias.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pmq *ProfissionalMateriasQuery) IDsX(ctx context.Context) []int {
	ids, err := pmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pmq *ProfissionalMateriasQuery) Count(ctx context.Context) (int, error) {
	if err := pmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return pmq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (pmq *ProfissionalMateriasQuery) CountX(ctx context.Context) int {
	count, err := pmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pmq *ProfissionalMateriasQuery) Exist(ctx context.Context) (bool, error) {
	if err := pmq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return pmq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (pmq *ProfissionalMateriasQuery) ExistX(ctx context.Context) bool {
	exist, err := pmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProfissionalMateriasQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pmq *ProfissionalMateriasQuery) Clone() *ProfissionalMateriasQuery {
	if pmq == nil {
		return nil
	}
	return &ProfissionalMateriasQuery{
		config:      pmq.config,
		limit:       pmq.limit,
		offset:      pmq.offset,
		order:       append([]OrderFunc{}, pmq.order...),
		predicates:  append([]predicate.ProfissionalMaterias{}, pmq.predicates...),
		withMateria: pmq.withMateria.Clone(),
		// clone intermediate query.
		sql:  pmq.sql.Clone(),
		path: pmq.path,
	}
}

// WithMateria tells the query-builder to eager-load the nodes that are connected to
// the "materia" edge. The optional arguments are used to configure the query builder of the edge.
func (pmq *ProfissionalMateriasQuery) WithMateria(opts ...func(*MateriaQuery)) *ProfissionalMateriasQuery {
	query := &MateriaQuery{config: pmq.config}
	for _, opt := range opts {
		opt(query)
	}
	pmq.withMateria = query
	return pmq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (pmq *ProfissionalMateriasQuery) GroupBy(field string, fields ...string) *ProfissionalMateriasGroupBy {
	group := &ProfissionalMateriasGroupBy{config: pmq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := pmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return pmq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (pmq *ProfissionalMateriasQuery) Select(fields ...string) *ProfissionalMateriasSelect {
	pmq.fields = append(pmq.fields, fields...)
	return &ProfissionalMateriasSelect{ProfissionalMateriasQuery: pmq}
}

func (pmq *ProfissionalMateriasQuery) prepareQuery(ctx context.Context) error {
	for _, f := range pmq.fields {
		if !profissionalmaterias.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pmq.path != nil {
		prev, err := pmq.path(ctx)
		if err != nil {
			return err
		}
		pmq.sql = prev
	}
	return nil
}

func (pmq *ProfissionalMateriasQuery) sqlAll(ctx context.Context) ([]*ProfissionalMaterias, error) {
	var (
		nodes       = []*ProfissionalMaterias{}
		withFKs     = pmq.withFKs
		_spec       = pmq.querySpec()
		loadedTypes = [1]bool{
			pmq.withMateria != nil,
		}
	)
	if pmq.withMateria != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, profissionalmaterias.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &ProfissionalMaterias{config: pmq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, pmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := pmq.withMateria; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*ProfissionalMaterias)
		for i := range nodes {
			if nodes[i].materia_profissional_materias == nil {
				continue
			}
			fk := *nodes[i].materia_profissional_materias
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(materia.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "materia_profissional_materias" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Materia = n
			}
		}
	}

	return nodes, nil
}

func (pmq *ProfissionalMateriasQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pmq.querySpec()
	_spec.Node.Columns = pmq.fields
	if len(pmq.fields) > 0 {
		_spec.Unique = pmq.unique != nil && *pmq.unique
	}
	return sqlgraph.CountNodes(ctx, pmq.driver, _spec)
}

func (pmq *ProfissionalMateriasQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := pmq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (pmq *ProfissionalMateriasQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   profissionalmaterias.Table,
			Columns: profissionalmaterias.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: profissionalmaterias.FieldID,
			},
		},
		From:   pmq.sql,
		Unique: true,
	}
	if unique := pmq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := pmq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, profissionalmaterias.FieldID)
		for i := range fields {
			if fields[i] != profissionalmaterias.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pmq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pmq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pmq *ProfissionalMateriasQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pmq.driver.Dialect())
	t1 := builder.Table(profissionalmaterias.Table)
	columns := pmq.fields
	if len(columns) == 0 {
		columns = profissionalmaterias.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pmq.sql != nil {
		selector = pmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pmq.unique != nil && *pmq.unique {
		selector.Distinct()
	}
	for _, p := range pmq.predicates {
		p(selector)
	}
	for _, p := range pmq.order {
		p(selector)
	}
	if offset := pmq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pmq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProfissionalMateriasGroupBy is the group-by builder for ProfissionalMaterias entities.
type ProfissionalMateriasGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pmgb *ProfissionalMateriasGroupBy) Aggregate(fns ...AggregateFunc) *ProfissionalMateriasGroupBy {
	pmgb.fns = append(pmgb.fns, fns...)
	return pmgb
}

// Scan applies the group-by query and scans the result into the given value.
func (pmgb *ProfissionalMateriasGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := pmgb.path(ctx)
	if err != nil {
		return err
	}
	pmgb.sql = query
	return pmgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pmgb *ProfissionalMateriasGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := pmgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (pmgb *ProfissionalMateriasGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(pmgb.fields) > 1 {
		return nil, errors.New("ent: ProfissionalMateriasGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := pmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pmgb *ProfissionalMateriasGroupBy) StringsX(ctx context.Context) []string {
	v, err := pmgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pmgb *ProfissionalMateriasGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pmgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profissionalmaterias.Label}
	default:
		err = fmt.Errorf("ent: ProfissionalMateriasGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pmgb *ProfissionalMateriasGroupBy) StringX(ctx context.Context) string {
	v, err := pmgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (pmgb *ProfissionalMateriasGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(pmgb.fields) > 1 {
		return nil, errors.New("ent: ProfissionalMateriasGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := pmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pmgb *ProfissionalMateriasGroupBy) IntsX(ctx context.Context) []int {
	v, err := pmgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pmgb *ProfissionalMateriasGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pmgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profissionalmaterias.Label}
	default:
		err = fmt.Errorf("ent: ProfissionalMateriasGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pmgb *ProfissionalMateriasGroupBy) IntX(ctx context.Context) int {
	v, err := pmgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (pmgb *ProfissionalMateriasGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(pmgb.fields) > 1 {
		return nil, errors.New("ent: ProfissionalMateriasGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := pmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pmgb *ProfissionalMateriasGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := pmgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pmgb *ProfissionalMateriasGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pmgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profissionalmaterias.Label}
	default:
		err = fmt.Errorf("ent: ProfissionalMateriasGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pmgb *ProfissionalMateriasGroupBy) Float64X(ctx context.Context) float64 {
	v, err := pmgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (pmgb *ProfissionalMateriasGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(pmgb.fields) > 1 {
		return nil, errors.New("ent: ProfissionalMateriasGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := pmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pmgb *ProfissionalMateriasGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := pmgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pmgb *ProfissionalMateriasGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pmgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profissionalmaterias.Label}
	default:
		err = fmt.Errorf("ent: ProfissionalMateriasGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pmgb *ProfissionalMateriasGroupBy) BoolX(ctx context.Context) bool {
	v, err := pmgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pmgb *ProfissionalMateriasGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range pmgb.fields {
		if !profissionalmaterias.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := pmgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pmgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pmgb *ProfissionalMateriasGroupBy) sqlQuery() *sql.Selector {
	selector := pmgb.sql.Select()
	aggregation := make([]string, 0, len(pmgb.fns))
	for _, fn := range pmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(pmgb.fields)+len(pmgb.fns))
		for _, f := range pmgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(pmgb.fields...)...)
}

// ProfissionalMateriasSelect is the builder for selecting fields of ProfissionalMaterias entities.
type ProfissionalMateriasSelect struct {
	*ProfissionalMateriasQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (pms *ProfissionalMateriasSelect) Scan(ctx context.Context, v interface{}) error {
	if err := pms.prepareQuery(ctx); err != nil {
		return err
	}
	pms.sql = pms.ProfissionalMateriasQuery.sqlQuery(ctx)
	return pms.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pms *ProfissionalMateriasSelect) ScanX(ctx context.Context, v interface{}) {
	if err := pms.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (pms *ProfissionalMateriasSelect) Strings(ctx context.Context) ([]string, error) {
	if len(pms.fields) > 1 {
		return nil, errors.New("ent: ProfissionalMateriasSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := pms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pms *ProfissionalMateriasSelect) StringsX(ctx context.Context) []string {
	v, err := pms.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (pms *ProfissionalMateriasSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pms.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profissionalmaterias.Label}
	default:
		err = fmt.Errorf("ent: ProfissionalMateriasSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pms *ProfissionalMateriasSelect) StringX(ctx context.Context) string {
	v, err := pms.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (pms *ProfissionalMateriasSelect) Ints(ctx context.Context) ([]int, error) {
	if len(pms.fields) > 1 {
		return nil, errors.New("ent: ProfissionalMateriasSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := pms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pms *ProfissionalMateriasSelect) IntsX(ctx context.Context) []int {
	v, err := pms.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (pms *ProfissionalMateriasSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pms.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profissionalmaterias.Label}
	default:
		err = fmt.Errorf("ent: ProfissionalMateriasSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pms *ProfissionalMateriasSelect) IntX(ctx context.Context) int {
	v, err := pms.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (pms *ProfissionalMateriasSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(pms.fields) > 1 {
		return nil, errors.New("ent: ProfissionalMateriasSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := pms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pms *ProfissionalMateriasSelect) Float64sX(ctx context.Context) []float64 {
	v, err := pms.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (pms *ProfissionalMateriasSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pms.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profissionalmaterias.Label}
	default:
		err = fmt.Errorf("ent: ProfissionalMateriasSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pms *ProfissionalMateriasSelect) Float64X(ctx context.Context) float64 {
	v, err := pms.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (pms *ProfissionalMateriasSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(pms.fields) > 1 {
		return nil, errors.New("ent: ProfissionalMateriasSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := pms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pms *ProfissionalMateriasSelect) BoolsX(ctx context.Context) []bool {
	v, err := pms.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (pms *ProfissionalMateriasSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pms.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profissionalmaterias.Label}
	default:
		err = fmt.Errorf("ent: ProfissionalMateriasSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pms *ProfissionalMateriasSelect) BoolX(ctx context.Context) bool {
	v, err := pms.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pms *ProfissionalMateriasSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := pms.sql.Query()
	if err := pms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
