// Code generated by entc, DO NOT EDIT.

package unidade

const (
	// Label holds the string label denoting the unidade type in the database.
	Label = "unidade"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDescricao holds the string denoting the descricao field in the database.
	FieldDescricao = "descricao"
	// FieldURLAmigavel holds the string denoting the url_amigavel field in the database.
	FieldURLAmigavel = "url_amigavel"
	// FieldEnderecoID holds the string denoting the endereco_id field in the database.
	FieldEnderecoID = "endereco_id"
	// FieldLatitude holds the string denoting the latitude field in the database.
	FieldLatitude = "latitude"
	// FieldLongitude holds the string denoting the longitude field in the database.
	FieldLongitude = "longitude"
	// FieldTelefone holds the string denoting the telefone field in the database.
	FieldTelefone = "telefone"
	// FieldCelular holds the string denoting the celular field in the database.
	FieldCelular = "celular"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldFacebook holds the string denoting the facebook field in the database.
	FieldFacebook = "facebook"
	// FieldInstagram holds the string denoting the instagram field in the database.
	FieldInstagram = "instagram"
	// FieldYoutube holds the string denoting the youtube field in the database.
	FieldYoutube = "youtube"
	// FieldAtivo holds the string denoting the ativo field in the database.
	FieldAtivo = "ativo"
	// Table holds the table name of the unidade in the database.
	Table = "unidades"
)

// Columns holds all SQL columns for unidade fields.
var Columns = []string{
	FieldID,
	FieldDescricao,
	FieldURLAmigavel,
	FieldEnderecoID,
	FieldLatitude,
	FieldLongitude,
	FieldTelefone,
	FieldCelular,
	FieldEmail,
	FieldFacebook,
	FieldInstagram,
	FieldYoutube,
	FieldAtivo,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
